export const payments = [
  {
    mesReferencia: 'Outubro',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '07/11/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Setembro',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '06/10/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Agosto',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '06/09/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
  {
    mesReferencia: 'Julho',
    Tipo: 'Folha Mensal e Ferias',
    dataPagamento: '05/08/2023',
    liquido: 1000,
  },
];
